name: Drive Web CI Automation Test

on: 
    push:
        branches:
            - feat/E2E-Testing-automation-internxt

defaults:
   run:
    working-directory: ./automation-drive-web
jobs:
    Build-Cypress-TestSuite-AfterPush:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16
                registry-url: 'https://npm.pkg.github.com'

            - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
            - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc

            - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
            - run: echo "always-auth=true" >> .npmrc

            - name: Install All Dependencies
              run: |
                  yarn

            - name: Cypress Run
              uses: cypress-io/github-action@v6
              with:
                browser: chrome
                command: yarn file "cypress/e2e/spec.cy.js" 
