name: Drive Web CI Automation Test

on: 
    push:
        branches:
            - feat/E2E-Testing-automation-internxt

jobs:
    Build-Cypress-TestSuite-AfterPush:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
                registry-url: 'https://npm.pkg.github.com'

            - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
            - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc

            - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
            - run: echo "always-auth=true" >> .npmrc

            - name: Install All Dependencies
              run: |
                  yarn

            - name: Cypress Run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  command: | 
                      yarn file automation-drive-web/cypress/e2e/spec.cy.js
