name: Drive Web CI Automation Test

on: 
    push:
        branches:
            - feature/AFS-E2E-Testing-Automation-Internxt

jobs:
    Build-Cypress-TestSuite-AfterPush:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x]
            
        environment:
          name: test    

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set Working Directory
              run: cd automation-drive-web
              

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16
                registry-url: 'https://npm.pkg.github.com'

            - name: Set Working Directory
              run: cd automation-drive-web

            - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
            - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc

            - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
            - run: echo "always-auth=true" >> .npmrc

            - name: Install All Dependencies
              run: |
                  cd automation-drive-web
                  yarn

            - name: Cypress Run
              uses: cypress-io/github-action@v6
              with:
                working-directory: automation-drive-web
                browser: chrome
                command: yarn file "cypress/e2e/feature/AFS-Folder-Creation-and-Initial-Sharing/AFS-Folder-Creation.cy.ts"
              env:
                TESTING_MAINACCOUNT: ${{ secrets.TESTING_MAINACCOUNT }}
                TESTING_EDITORACCOUNT: ${{ secrets.TESTING_EDITORACCOUNT }}
                TESTING_READERACCOUNT: ${{ secrets.TESTING_READERACCOUNT }}
                TESTING_PASSWORD: ${{ secrets.TESTING_PASSWORD }}   
