name: CI run (BUILD) Test Suite Execution


on: 
    push:
        branches:
            - feat/E2E-Testing-automation-internxt

jobs:
    Build-Cypress-TestSuite-AfterPush:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc


            - name: Cypress Run Test Coverage in Chrome
              uses: cypress-io/github-action@v4
              with:
                  browser: chrome
                  command: | 
                      yarn file cypress/e2e/spec.cy.js
